### ISSUE TITLE
Documentation for Dev_SDCard_Program.L5X

### ISSUE THREAD

**Issue by aliksimon** [JeremyMedders/LogixLibraries#7]
Hi Jeremy,
maybe you wrote a very helpful bit of code but unfortunately I cannot figure out what it does and how to use it:
src/System/Dev_SDCard_Program.L5X

I would like to read data from a file on the SD Card. In case your code should do this,
- where do I input the filename?
- where is the content of the file saved?
- where did you get the magic numbers from and what do they mean? (e.g. `Msg.AttrAll.Class = 16#031a`, `MsgAttrAll.Flags = 16#0200`, `MsgAttrAll.Path = '$1F$00$00$00'`, the values in `MsgAttrAllResp`, `16#031A` in line 13 of Sys_SDCard)

I've also found the Sample Code `CF_Read_Write_Example` from Rockwell but it gave an error when importing for our controller and it's far more complicated to understand (because of Ladder Code and the size and number of routines) and blows up the code due to the many routines instead of nice AOIs.) So it would be great to be able to use your code.

If it's simpler for you to write a bit here than making a proper documentation in the [Wiki](https://github.com/JeremyMedders/LogixLibraries/wiki) I will make a PR for writing this documentation and probably add some comments to the code that would have helped me.

**Comment by JeremyMedders** [comment]
Hi, aliskimon!

Apologies for my hiatus. I am in the process of a documentation (and overall) overhaul of content here.

I agree that Rockwell sample code can sometimes be cumbersome and confusing to understand.

My SDCard AOI, then and currently parses info from a Rockwell CIP object:
- Class code is 0x31A.
- Instance Id is 1.
- Uses the CIP Get_Attributes_All service (0x01).
- Msg.Attribute Id is set to zero for this service.
- Msg.ReqLen is also set to zero for this service.
- No need to worry about the Msg.Flags, and I rarely interact with them beyond diagnostics.
 
Within the SDCard block, a couple of utility AOIs are used to set these parameters: 
```
Msg_SetParams(SetParams, 16#031A, 1, 0, 0, Ref_Msg);
Msg_SetPathToIO(SetPath, Ref_Module, Ref_Msg);
MSG(Ref_Msg);
```

- Msg_SetParams() sets the parameters mentioned above: CIP Class, Instance, Attribute, and RequestLength.
- Msg_SetPathToIO() handles setting the Msg.Path to the correct destination, using a MODULE reference.

The MODULE reference is provided at the point of the AOI call ('Local' refers to the controller itself):
![image](https://github.com/JeremyMedders/LogixLibraries/assets/122491027/1caba064-0c7f-40ad-8f45-b9ca933e0bb7)

**Comment by JeremyMedders** [comment]
To further add, the current AOI doesn't do any sort of file handling.

I am working a general-purpose version of this.
